### PR TITLE
[Doc] Tweak README to clarify inference/inflector configuration

### PR DESCRIPTION
**Pull request by trevorturk**
When working on #258 I found the documentation to be a bit confusing. I tried to tidy things up a bit here with the following changes:

* Consolidate "inference" and "inference configuration" into one section
* Link to "inference configuration" when relevant
* Rename "inference" section and link it to "inference configuration"
* Prefer the word "inference" to the word "inflector" where possible

FWIW I still find the language a bit awkward. I was expecting Alba to expose a different API for configuring inference/inflection. Perhaps it's confusing because we configure the "inflector" for both "inflection" and "inference" but I'm not sure if it's worth making a big change. 

To illustrate a possible option, we could imagine changing the API from the first to the second:

```ruby
Alba.enable_inference!(with: :active_support)
Alba.inflector = :active_support
```

...and then you would be expected to set the `inflector` to enable both features. This might make sense since the gems Alba has built-in support for both use the term "inflector" in their names. 

Also re: #258 I understand the desire to remove the automatically-set inflector, but I personally preferred to have that set for me, since it meant I didn't need an initializer. 

In any case, feel free to discard this PR if you choose. I just wanted to provide some feedback for what I ran into when upgrading to Alba 2.0. Thank you!

### CODE REVIEW

**Comment by okuramasafumi** [comment]
Actually I also thought the wordings around inflection is confusing, and I think we need to deprecate some APIs in favor of more straightforward ones.

```ruby
Alba.inflector = :active_support
```

I prefer this API.

> I understand the desire to remove the automatically-set inflector, but I personally preferred to have that set for me, since it meant I didn't need an initializer.

For example, what if we have both `active_support` and `dry-inflector` at the same time? I'd let users to choose one since it's less surprising.

One possible and maybe better solution is to add some file called `rails.rb` with something like this:

```ruby
if defined?(Rails)
  # common Rails initializer content is here
end
```

so that they don't have to write the same initializer. This way, we can choose `active_support` as an inflector for Rails environment only where they feel natural, and for other environments such as Sinatra, we let users to choose.

**Comment by trevorturk** [comment]
That's great, I think a more simple API would be nice, but I can see it would be a fair amount of work to adjust the code, so I understand if you decide to leave that as-is, of course. 

Also, it's not a big deal to require setting the inference/inflector, but I think it's a nice-to-have if you're using a framework (or have a gem installed) to pick a default. The more default settings / less configuration for the "happy path" the better. 

I think your idea about checking `defined?` makes sense. I could see a more complex version like this, but perhaps it doesn't need to be so complex:

```ruby
def find_default_inflector
  if defined?(Dry::Inflector)
    :dry_inflector
  elsif defined?(ActiveSupport)
    :active_support
  else
    begin
      require 'dry/inflector'
      return :dry_inflector
    rescue LoadError
    end
    begin
      require 'active_support/inflector'
      return :active_support
    rescue LoadError
    end
    raise "nice error message"
  end
end
```

I think it might make sense to put `Hanami` and/or `Dry::Inflector` first in the logic, because if you're using one of those gems, I'd guess you'd prefer to use that instead of `ActiveSupport`, even if you had it installed for some other reason. Still, since you could always set this inflector manually, I think a simple setup that attempts to find a default for the "happy path" would be totally fine.

**Comment by okuramasafumi** [comment]
@trevorturk I tried to simplify APIs in #265
I have not implemented it yet, but I think picking the default inflector should be based on framework only. I like your idea of using `defined?`, so it might look like:

```ruby
if defined?(Rails)
  :active_support
elsif defined?(Hanami)
  :dry
end
```

**Comment by trevorturk** [comment]
I think #265 is looking great. I think the simplification is working well, and your API is very easy to understand. 

I like the framework-picker idea just fine. Really any "smart" defaults I think are nice, so you have convention over configuration, but still configurable. 

Please feel free to close this PR since it's likely only interesting for reference perhaps for README updates. I'm also happy to draft documentation if you like. Thank you!

**Comment by okuramasafumi** [comment]
@trevorturk Sorry for asking fixes many times, but could you resolve the conflict? It looks like the entry for `2.0.1` and `unreleased` conflict.

**Comment by trevorturk** [comment]
No problem at all! I just did a merge conflict fix on GitHub, if that's ok. If you'd prefer a single commit, perhaps you can use GitHub's "squash and merge" button, or I'd be happy to pull this down and unify into a single commit.

**Pull request merged**
