### PR TITLE
Add jsonapi-serializer gem to benchmark and clean up the file

### PR DESCRIPTION
**Pull request by mediafinger**
Hey, I like your simple gem and that it includes a benchmark with various other gems. I was missing the **jsonapi-serializers** (formerly known as _fast_jsonapi_) gem and therefore I've added it.  I've also added `benchmark/ips` and refactored the benchmark file (sorting calls and declarations alphabetically and adding some comments to make it simpler to understand the file).

Ok, now you might wonder: _"but jsonapi-serializers formats the output differently"_ and you would be correct. But as I've done in a few projects before, where some endpoints needed a simple, 'flat' serialization and didn't follow the JSON:API standard, I've overwritten its `as_json` method to get the same output as with the other serializers.

And it is still fast, almost as fast as **alba**.

---

> _I recommend to review this **commit by commit** as this will make it easier to understand the changes._ 
>
> _Looking at the final version of [benchmark/local.rb](https://github.com/okuramasafumi/alba/blob/12640c6afa066c1a753dbd5412ff797853d9fb98/benchmark/local.rb) might also be easier than trying to understand the diff in which I moved multiple blocks and lines up or down to sort them alphabetically._

--- 

**benchmark/ips output:**

```log
Comparison:
            jbuilder:     4676.4 i/s
                alba:     4666.7 i/s - same-ish: difference falls within error
 jsonapi_same_format:     4433.5 i/s - 1.05x  (± 0.00) slower
         blueprinter:     4250.1 i/s - 1.10x  (± 0.00) slower
             jsonapi:     4089.7 i/s - 1.14x  (± 0.00) slower
       representable:     4073.6 i/s - 1.15x  (± 0.00) slower
                 ams:     3651.2 i/s - 1.28x  (± 0.00) slower
         alba_inline:     3330.4 i/s - 1.40x  (± 0.00) slower
               rails:     2641.7 i/s - 1.77x  (± 0.00) slower
```

---

PS: I've got the idea from a tweet of @jgaskins who started to expand the benchmark (but didn't open a PR yet):  
https://github.com/jgaskins/alba/commit/ad78703e844868c549cc5cf445bd7b7d2e3616e4

### CODE REVIEW

**Comment by okuramasafumi** [comment]
Awesome! I also thought benchmark script should be cleaned up. Thank you!

I know there are a variety of gems that also render JSON:API compatible JSON described in https://github.com/jsonapi-serializer/comparisons
Do you think it's worth adding them? If we add them the benchmark would be even more useful for some people, but it also gets slower to execute.
If they only support JSON:API and cannot serialize into plain JSON, it won't be a fair comparison, though.

**Comment by mediafinger** [comment]
Glad you like it :-)

> _If they only support JSON:API and cannot serialize into plain JSON, it won't be a fair comparison, though._

I think that as the main issue. In the case of fast_jsonapi / jsonapi-serializer I knew how to make it output plain JSON, as I was using it in several projects. But for the other gems, I would not directly know how or if possible at all.

**Comment by okuramasafumi** [comment]
I see, well I'm merging this now!

**Comment by stas** [comment]
Related https://github.com/okuramasafumi/alba/issues/104#issuecomment-891035096

Please revert this. :bow:

**Pull request merged**
