### PR TITLE
[Feat] Rails integration to set default inflector

### PR DESCRIPTION
**Pull request by okuramasafumi**
This is a temporary implementation of how to automatically set default inflector with Rails.
I haven't tested with user-defined inflector setting.

### CODE REVIEW

**Comment by trevorturk** [comment]
This seems fine to me as an alternative to #274. You could consider `Alba.inflector ||= :active_support` in case the user somehow wants to set it a different way and this runs first. Note in the other PR I did `before_initialize`, but I think this is fine and probably more typical anyway.

**Comment by okuramasafumi** [comment]
@trevorturk I think this works OK, could you try it in real Rails apps? If this works I'll add Hanami integration in separate PR.

**Comment by trevorturk** [comment]
Yes, this works perfectly for me. It's set by default, and if you want to configure `Dry::Inflector` it works as well:

```
irb(main):001:0> Alba.inflector
=> Alba::DefaultInflector

#...and with
# config/initializers/alba.rb
Alba.inflector = :dry

irb(main):001:0> Alba.inflector
=> #<Dry::Inflector>
```

**Comment by okuramasafumi** [comment]
@trevorturk Could you also check if it works with user-defined initializer? For example,

```ruby
# config/initializers/alba.rb
Alba.inflector = :dry
```

**Comment by okuramasafumi** [comment]
Awesome, thank you!

**Comment by trevorturk** [comment]
🥳

**Pull request merged**
